### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by johaven** [hrueger/ngx-onlyoffice#50]
console.log do not relay message or events :)

**Comment by hrueger** [comment]
Hi,
I'll look into that tomorrow.

**Comment by hrueger** [comment]
I updated all the packages to Angular 10 and released `v0.0.6`. Do the events work for you with that version?

For me they do, although I haven't really changed any logic ;-)

**Comment by hrueger** [comment]
@johaven Do you still encounter that problem or can I close this issue?

**Comment by johaven** [comment]
Sorry, i will check that in the next days !

**Comment by parthrana4** [comment]
npm ERR! Refusing to install package with name "ngx-onlyoffice" under a package
npm ERR! also called "ngx-onlyoffice". Did you name your project the same
npm ERR! as the dependency you're installing? @hrueger can you help
