### ISSUE TITLE
onSave is deprecated 

### ISSUE THREAD

**Issue by Eren1000** [hrueger/ngx-onlyoffice#63]
It seems that onlyoffice has deprecated the onSave event and recommends using the callbackUrl now. The issue I am having is that when trying to include callbackUrl within the editorConfig, typescript is throwing a type error because 'callbackUrl' is not a property that is expected in the editorConfig object. In the source code, editorConfig appears to be of type 'any' but for some reason is enforcing a type during runtime. Do you have any suggestions on what I could change so that 'callbackUrl' can be included in the editorConfig object?

**Comment by hrueger** [comment]
You need tu put the `callbackUrl` property into the inner `editorConfig` object. Example: https://github.com/SchoolSquirrel/SchoolSquirrel/blob/a3ed3ed72392308b340ac30ac24b8c0f441ae4da/SchoolSquirrel/src/app/_pages/edit-document/edit-document.component.ts#L109
Does that help?

**Comment by Eren1000** [comment]
It works, thank you!
